Feat/ggircs app
bcgov/cas-ggircs pull request #200
Opened 2021-01-20 00:13 UTC by matthieu-foucault

2021-01-29 00:34 UTC, dleard requested changes
can we get rid of all the test/data/Report_xxx files?

2021-01-29 16:43 UTC, matthieu-foucault commented on ggircs-app/app/.env
> +SESSION_SECRET=blah
This file was committed before adding the line in .gitignore, which is why it shows up

2021-01-29 16:44 UTC, matthieu-foucault commented
The  `test/data/Report_xxx` files are used in cas-ciip-portal. We should probably have tests using them in this repository

2021-02-03 20:52 UTC, pbastia approved these changes

2021-02-03 20:52 UTC, pbastia commented on ggircs-app/app/server/routers/sso.js
> +  // }
we can probably delete this

2021-02-03 22:53 UTC, pbastia approved these changes

2021-02-03 22:56 UTC, merged