feat: create swrs_history schema
bcgov/cas-ggircs pull request #298
Opened 2021-08-10 22:10 UTC by naomiaro

2021-08-11 23:25 UTC, dleard commented on deploy/swrs/history/table/attachments.sql
> +    report_id                 integer
zip_file_id,
attachment_name,
download_link?

2021-08-19 17:49 UTC, matthieu-foucault requested changes

2021-08-19 17:49 UTC, matthieu-foucault commented on deploy/swrs/history/schema.sql
> +COMMIT;
lowercase begin/commit

2021-08-19 17:49 UTC, matthieu-foucault commented on deploy/swrs/history/table/report.sql
> +    update_comment            varchar(1000),
we had to increase this to `100000`

2021-08-19 17:49 UTC, matthieu-foucault commented on test/unit/materialized_view_historical_report_emission_data_test.sql
> +      <TotalEmissions>
Looking at some sample reports `TotalEmissions` is sometimes empty, and when it is not the `TotalGroupType` values are not necessarily the same as what you have here. I don't think this is actually needed here either

2021-08-19 18:37 UTC, matthieu-foucault commented on test/unit/materialized_view_historical_report_emission_data_test.sql
> +      <TotalEmissions>
Nevermind this comment actually. If the total is 0 in the existing spreadsheet, then it will be 0 here as well.

2021-08-19 18:37 UTC, matthieu-foucault approved these changes

2021-08-19 19:00 UTC, merged