Chore: Keycloak gold migration
bcgov/cas-ggircs pull request #480
Opened 2022-12-16 21:32 UTC by pbastia

2023-01-03 22:43 UTC, dleard requested changes
The create user function is never called, so we aren't getting any users inserted into the database. It looks like in CIF we created a createUser middleware, I added a link in my comment in the sso middlware.

Also found a sqitch order gotcha that we won't catch in dev because we have no users.

2023-01-03 22:43 UTC, dleard commented on ggircs-app/app/server/middleware/sso.js
> +    },
The user is never created on login. I think we're missing a createUser middleware & an `onAuthCallback: createUserMiddleware()` call here.
See CIF implementation [here](https://github.com/bcgov/cas-cif/blob/develop/app/server/middleware/sso.ts#L54)

2023-01-04 21:15 UTC, pbastia commented on ggircs-app/schema/deploy/tables/eccc_file_download_log.sql
> +create or replace function ggircs_app_private.eccc_file_download_log_insert()
Yes, that makes more sense 👍

2023-01-18 22:33 UTC, dleard approved these changes

2023-01-18 22:34 UTC, merged